services:
  - type: web
    name: tisket-api
    runtime: docker
    plan: free
    region: ohio
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    healthCheckPath: /health
    envVars:
      - key: APP_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
